source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import ProfileView, RegisterView, UserEditView, UserPasswordChangeView


app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>/edit/', UserEditView.as_view(), name='edit_user'),
    path('profile/<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='user_password_change'),
]

source/board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urls_app = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include(urls_app)),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator


class AppUser(AbstractUser):
    email = models.EmailField(max_length=30, unique=True, null=False, blank=False, verbose_name="Email")
    avatar = models.ImageField(upload_to='user_pics', verbose_name='Avatar')
    phone = models.CharField(max_length=16, validators=[MinLengthValidator(16)], null=False, blank=False, verbose_name="Phone number")
    ads_count = models.IntegerField(default=0, verbose_name='Ads count')
    comments_count = models.IntegerField(default=0, verbose_name='Comments count')

    def __str__(self):
        return f'{self.first_name} {self.last_name}, username: {self.username}'

source/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth import get_user_model

from .models import AppUser


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = AppUser
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'phone', 'avatar')


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email', 'phone', 'avatar']

source/accounts/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import DetailView, CreateView, UpdateView
from django.contrib.auth import get_user_model, login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import Q

from .forms import MyUserCreationForm, UserChangeForm
from webapp.helper import Message


class ProfileView(DetailView):
    model = get_user_model()
    template_name = 'profile.html'
    context_object_name = 'user_obj'
    paginate_related_by = 10
    paginate_related_orphans = 1

    def get_context_data(self, **kwargs):
        if self.request.user.pk == self.kwargs.get('pk'):
            ads = self.object.ads.filter(Q(status='1') | Q(status='2') | Q(status='3'))
        else:
            ads = self.object.ads.filter(status='2')
        paginator = Paginator(ads, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['ads'] = page.object_list
        kwargs['is_paginated'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class RegisterView(CreateView):
    model = get_user_model()
    form_class = MyUserCreationForm
    template_name = 'registration.html'

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:index')


class UserEditView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_update.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('accounts:profile', pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(UserPassesTestMixin, PasswordChangeView):
    template_name = 'user_password_change.html'

    def test_func(self):
        return self.request.user.pk == self.kwargs.get('pk')

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('accounts:profile', pk=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('accounts:profile', kwargs={'pk': self.request.user.pk})

source/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Log in{% endblock %}
{% block content %}
    <h1>Log in</h1>
    {% if not request.user.is_authenticated %}
        <form action="{% url 'accounts:login' %}" method="post" class="text-center" id="loginForm">
            {% csrf_token %}
            {% if has_error %}
                <p class="form-error">Wrong email or password</p>
            {% endif %}
            <div class="form-group">
                <label for="username" class="form-label">Login:</label>
                <input type="text" name="username" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Password:</label>
                <input type="password" name="password" id="password">
            </div>
            <button type="submit">Log in</button>
        </form>
    {% else %}
        <p>You entered as {{user}}</p>
    {% endif %}
{% endblock %}

{% block script %}
    <script>
        async function makeRequest(url, method='GET', data={}, token=null) {
            let headers = {
                "Content-Type": "application/json"
            };
            if (token) {
                headers['Authorization'] = 'Token ' + token;
            }
            let body = JSON.stringify(data);
            let response = await fetch(url, {method, headers, body: JSON.stringify(data)});
            if (response.ok) {
                return await response.json();
            } else {
                let error = new Error(response.statusText);
                error.response = response;
                throw error;
            }
        }

        async function onSubmit(e) {
            e.preventDefault();
            console.log(e.target);
            let username = e.target.username.value;
            let password = e.target.password.value;
            try {
                let response = await makeRequest(
                'http://127.0.0.1:8000/api/v1/login/',
                "POST",
                {
                 "username": username,
                 "password": password
                 }
                );
                console.log(response);
                localStorage.setItem('apiToken', response.token);
            } finally {
                e.target.submit();
            }
        }

        async function onLoad() {
            let loginForm = document.getElementById('loginForm');
            loginForm.addEventListener('submit', onSubmit);

        }

        window.addEventListener('load', onLoad);
    </script>
{% endblock %}

source/accounts/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User: {{ user_obj.get_full_name }}{% endblock %}
{% block content %}
    <h1>User</h1>
    {% include "partial/messages.html" %}
    <div class="card mb-3">
        <div class="card-body">
            <img src="{% if user_obj.avatar %}{{ user_obj.avatar.url }}{% else %}{% static 'img/default_user.jfif' %}{% endif %}" class="card-img-top w-50 mx-auto" alt="{{ ad.user_obj.username }}">
            <h1>Personal page: {{ user_obj.get_full_name|default:user_obj.username }}</h1>
            <h5 class="card-title">{{ user_obj.username }}</h5>
            <p class="card-text">{{ user_obj.first_name }} {{ user_obj.last_name }} | {{ user_obj.email }}</p>
            <p class="card-text">{{ user_obj.phone }}</p>
            {% if request.user.pk == user_obj.pk %}
                <a href="{% url 'accounts:edit_user' user_obj.pk %}" >Edit user</a><br>
                <a href="{% url 'accounts:user_password_change' user_obj.pk %}" >Change password</a>
            {% endif %}
        </div>
        {% include 'partial/ads_list.html'%}
    </div>
{% endblock %}

source/accounts/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Registration{% endblock %}

{% block prescript %}
    <script src="https://unpkg.com/imask"></script>
{% endblock %}

{% block content %}
<h1>Registration</h1>
    {% if not request.user.is_authenticated %}
        {% include 'partial/form.html' with value_submit='Registration' form_method='post' enctype='multipart/form-data' %}
    {% else %}
        <p>You entered as {{user}}</p>
    {% endif %}
{% endblock %}

{% block script %}
    {% if not request.user.is_authenticated %}
        <script>
            IMask(document.querySelector('#id_phone'), {
              mask: '+{996}(000)000-000',
            });
        </script>
    {% endif %}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}Change password{% endblock %}
{% block content %}
    <h1>Change password</h1>
    {% url "accounts:password_change" user_obj.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" value_submit='Change password' %}
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User update{% endblock %}

{% block prescript %}
    <script src="https://unpkg.com/imask"></script>
{% endblock %}

{% block content %}
    <h1>User update</h1>
    {% include 'partial/form.html' with value_submit='User change' form_method='post' enctype='multipart/form-data' %}
{% endblock %}

{% block script %}
    <script>
        IMask(document.querySelector('#id_phone'), {
          mask: '+{996}(000)000-000',
        });
    </script>
{% endblock %}