source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import ProfileView, RegisterView, UserEditView, UserPasswordChangeView


app_name = 'accounts'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', ProfileView.as_view(), name='profile'),
    path('registration/', RegisterView.as_view(), name='registration'),
    path('profile/<int:pk>/edit/', UserEditView.as_view(), name='edit_user'),
    path('profile/<int:pk>/password_change/', UserPasswordChangeView.as_view(), name='user_password_change'),
]

source/api_v1/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token

from .views import ModerationView, LogoutView, CommentModelViewSet


app_name = 'api_v1'

router = routers.DefaultRouter()
router.register(r'comments', CommentModelViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('moderation/<int:pk>/', ModerationView.as_view(), name='moderation'),
    path('login/', obtain_auth_token, name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

source/board/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urls_app = [
    path('v1/', include('api_v1.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include(urls_app)),
    path('', include('webapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from .views import IndexView, AdCreateView, AdView, AdUpdateView, AdDeleteView, NoModerateAdsView


app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('ad/add/', AdCreateView.as_view(), name='ad_create'),
    path('ad/<int:pk>/', AdView.as_view(), name='ad_view'),
    path('ad/<int:pk>/update/', AdUpdateView.as_view(), name='ad_update_view'),
    path('ad/<int:pk>/delete/', AdDeleteView.as_view(), name='ad_delete_view'),
    path('ad/no_moderate/', NoModerateAdsView.as_view(), name='no_moderate_list'),
]

source/webapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model


STATUSES = [('1', 'Moderate'), ('2', 'Approve'), ('3', 'Rejection'), ('4', 'On delete')]
USER = get_user_model()


class AbstractModel(models.Model):
    created_at = models.DateTimeField(verbose_name="Created at", auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated at")

    class Meta:
        abstract = True


class Ad(AbstractModel):
    photo = models.ImageField(upload_to='publications_images', null=True, blank=True, verbose_name='Photo')
    title = models.CharField(max_length=50, null=False, blank=False, verbose_name="Title")
    description = models.TextField(max_length=500, null=True, blank=True, verbose_name="Description")
    author = models.ForeignKey(USER, null=False, blank=False, related_name='ads', on_delete=models.CASCADE, verbose_name="Author")
    category = models.ForeignKey('webapp.Category', related_name='ads', on_delete=models.CASCADE, verbose_name='Category')
    price = models.FloatField(default=0, verbose_name='Price')
    status = models.CharField(max_length=30, null=False, blank=False, verbose_name='Category', choices=STATUSES, default=1)
    published_at = models.DateTimeField(verbose_name="Published at", null=True, blank=True)

    class Meta:
        permissions = [
            ('see_no_moderate_ads', 'Can see no moderate ads'),
        ]

    def __str__(self):
        return f"This is ad {self.id}, {self.title}"

    def get_absolute_url(self):
        return reverse('webapp:ad_view', kwargs={'pk': self.pk})


class Category(models.Model):
    name = models.CharField(max_length=20,blank=False, null=False, verbose_name='Category name')

    def __str__(self):
        return self.name


class Comment(AbstractModel):
    text = models.TextField(max_length=500, null=False, blank=False, verbose_name='Comment')
    author = models.ForeignKey(USER, related_name='comments', null=False, blank=False, on_delete=models.CASCADE, verbose_name="Author")
    ad = models.ForeignKey('webapp.Ad', related_name='comments', on_delete=models.CASCADE, verbose_name='Ad')

    def __str__(self):
        return self.text[:20]

source/webapp/forms.py
from django import forms

from .models import Ad


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Find')


class AdForm(forms.ModelForm):
    class Meta:
        model = Ad
        fields = ('photo', 'title', 'description', 'category', 'price')
        error_messages = {
            'title': {
                'required': 'Please enter field'
            }
        }

source/webapp/views/ads_views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.db.models import Q
from django.utils.http import urlencode
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib import messages

from ..models import Ad
from ..forms import SimpleSearchForm, AdForm
from ..helper import Message


class IndexView(ListView):
    model = Ad
    template_name = 'ads/index.html'
    context_object_name = 'ads'
    paginate_by = 10
    paginate_orphans = 1
    ordering = ('-published_at',)

    def get_search_form(self):
        return SimpleSearchForm(self.request.GET)

    def get_search_value(self):
        if self.search_form.is_valid():
            return self.search_form.cleaned_data['search']
        return None

    def dispatch(self, request, *args, **kwargs):
        self.search_form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(title__icontains=self.search_value) |
                Q(description__icontains=self.search_value)
            )
        queryset = queryset.filter(status=2)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.search_form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
            context['search_value'] = self.search_value
        return context


class AdCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'ads/ad_create.html'
    model = Ad
    form_class = AdForm
    permission_required = 'webapp.add_ad'

    def form_valid(self, form):
        ad = form.save(commit=False)
        ad.author = self.request.user
        ad.save()
        return redirect('webapp:ad_view', pk=ad.pk)

    def has_permission(self):
        return self.request.user.is_authenticated

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('webapp:index')


class AdView(PermissionRequiredMixin, DetailView):
    model = Ad
    template_name = 'ads/ad_details.html'
    permission_required = 'webapp.view_ad'

    def has_permission(self):
        is_author = self.request.user == self.get_object().author
        is_approve = int(self.get_object().status) == 2
        is_delete = int(self.get_object().status) != 4
        is_other = int(self.get_object().status) not in [1, 3]
        if (is_approve or is_author) and (is_other or is_author) and is_delete:
            return True
        return False

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('webapp:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.order_by('-created_at')
        return context


class AdUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'ads/ad_update.html'
    model = Ad
    form_class = AdForm
    permission_required = 'webapp.change_ad'

    def form_valid(self, form):
        ad = form.save(commit=False)
        if ad.status == '2':
            ad.status = 1
        ad.save()
        return redirect('accounts:profile', pk=ad.author.pk)

    def has_permission(self):
        is_author = self.request.user == self.get_object().author
        is_delete = int(self.get_object().status) != 4
        is_rejection = int(self.get_object().status) != 3
        if is_delete and is_rejection and is_author:
            return True
        return False

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('webapp:ad_view', pk=self.get_object().pk)


class AdDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'ads/ad_delete.html'
    model = Ad
    permission_required = 'webapp.delete_ad'

    def post(self, request, *args, **kwargs):
        ad = get_object_or_404(Ad, pk=kwargs.get('pk'))
        ad.status = 4
        ad.save()
        return redirect('webapp:index')

    def has_permission(self):
        is_author = self.request.user == self.get_object().author
        is_delete = int(self.get_object().status) != 4
        if is_author and is_delete:
            return True
        return False

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('webapp:ad_view', pk=self.get_object().pk)


class NoModerateAdsView(PermissionRequiredMixin, ListView):
    template_name = 'ads/no_moderate_list.html'
    context_object_name = 'ads'
    paginate_by = 10
    paginate_orphans = 1
    permission_required = 'webapp.see_no_moderate_ads'

    def handle_no_permission(self):
        messages.add_message(self.request, messages.WARNING, Message.get_no_access_message())
        return redirect('webapp:index')

    def get_queryset(self):
        return Ad.objects.filter(status=1).order_by('-created_at')

source/webapp/templates/partial/ad_body.html
{% load static %}
{% if in_details %}
    <img src="{% if ad.photo %}{{ ad.photo.url }}{% else %}{% static 'img/ad.jpg' %}{% endif %}" class="card-img-top w-50 mx-auto" alt="{{ ad.title }}">
{% endif %}
<div class="card-body">
    <h5 class="card-title">{{ ad.title }}</h5>
    <p class="card-text"><b>Description: </b>{{ ad.description }}</p>
    <p class="card-text"><b>Author: </b><a href="{% url 'accounts:profile' pk=ad.author.pk %}" >{{ ad.author }}</a>, {{ ad.author.email }}</p>
    <p class="card-text"><b>Category: </b>{{ ad.category.name }}</p>
    <p class="card-text"><b>Price: </b>{{ ad.price }}</p>
    <p class="card-text">{{ ad.get_status_display }}</p>
    {% if to_details %}
        <a href="{% url 'webapp:ad_view' pk=ad.pk %}" class="card-link">Details</a>
    {% endif %}
    {% if in_details %}
        <p class="card-text">{{ ad.created_at }} | {{ ad.updated_at }} | {{ ad.published_at }}</p>
    {% endif %}
    {% if moderate %}
        <button type="button" class="nav-link border moderation-approve" data-action="approve" data-url="{% url 'api_v1:moderation' ad.pk %}">
            Approve
        </button>
        <button type="button" class="nav-link border moderation-reject" data-action="reject" data-url="{% url 'api_v1:moderation' ad.pk %}">
            Reject
        </button>
    {% endif %}
</div>

source/webapp/templates/partial/ads_list.html
<div>
    {% include 'partial/pagination.html' %}
</div>
<h1>Ads list</h1>
{% include "partial/messages.html" %}
{% for ad in ads %}
    <div class="card my-1">
        {% if moderate %}
            {% include 'partial/ad_body.html' with to_details=True moderate=True %}
        {% else %}
            {% include 'partial/ad_body.html' with to_details=True %}
        {% endif %}
    </div>
{% empty %}
    <p>No ads</p>
{% endfor %}

source/webapp/templates/partial/base_menu.html
{% if not request.user.is_authenticated %}
    <a class="nav-link" href="{% url 'accounts:login' %}" >Log in</a>
    <a class="nav-link" href="{% url 'accounts:registration' %}" >Registration</a>
{% else %}
    <a class="nav-link" href="{% url 'accounts:profile' pk=request.user.pk %}" >User {{user}} profile</a>
    <form id="logout-form" method="post" action="{% url 'accounts:logout' %}?next={{ request.path }}">
        {% csrf_token %}
        <button class="nav-link" type="submit">Log out({{ user }})</button>
    </form>
{% endif %}
{% if perms.webapp.change_ad or request.user.is_authenticated %}
    <a class="nav-link" href="{% url 'webapp:ad_create' %}">New ad</a>
{% endif %}
{% if perms.webapp.see_no_moderate_ads %}
    <a class="nav-link" href="{% url 'webapp:no_moderate_list' %}">Moderate list</a>
{% endif %}

source/webapp/templates/partial/detail_menu.html
{% if request.user == ad.author %}
    <a class="nav-link" href="{% url 'webapp:ad_update_view' pk=ad.pk %}">Update ad</a>
{% endif %}
{% if request.user == ad.author %}
    <a class="nav-link" href="{% url 'webapp:ad_delete_view' pk=ad.pk %}">Delete ad</a>
{% endif %}

source/webapp/templates/partial/form.html
<form action="{{ action_url }}" method="{{ form_method }}"  enctype="{{ enctype }}">
    {% csrf_token %}
    {% for error in form.non_field_errors %}
        <p class="text-danger">{{ error }}</p>
    {% endfor %}
    {% for field in form %}
        <label for="{{ field.id_for_label }}">{{ field.label }}:</label><br/>
        {{ field }}<br/>
        {% for error in field.errors %}
            <p class="tex-danger">{{ error }}</p>
        {% endfor %}
    {% endfor %}
    <br/>
    <input class="btn btn-light border border-black" type="submit" value="{{ value_submit }}"/>
</form>

source/webapp/templates/partial/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

source/webapp/templates/partial/pagination.html
<div class="pagination">
    <span class="step-links">
        <a href="?{% if query %}{{ query }}&{% endif %}page=1">&laquo; To begin</a>
        {% if page_obj.has_previous %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">To Back</a>
        {% else %}
            <span class="page-disabled">To Back</span>
        {% endif %}
        <form class="current-page" method="get">
            <label for="page">
                <input type="hidden" name="search" value="{{ search_value }}">
                Page <input type="text" name="page" id="page" value="{{ page_obj.number }}">
                from {{ page_obj.paginator.num_pages }}.
            </label>
        </form>
        {% if page_obj.has_next %}
            <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
        {% else %}
            <span class="page-disabled">Next</span>
        {% endif %}
        <a href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.paginator.num_pages }}">To end &raquo;</a>
    </span>
</div>

source/webapp/templates/partial/search.html
<form class="text-center" action="" method="GET">
    <label for="{{ form.search.id_for_label }}">{{ form.search.label }}:</label>
    {{ form.search }}
    <input type="submit" value="Search">
    {% for error in form.search.errors %}
        <p class="form-error">{{ error }}</p>
    {% endfor %}
</form>